apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-notes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi-notes
  template:
    metadata:
      labels:
        app: fastapi-notes
    spec:
      containers:
        - name: fastapi
          image: fastapi-notes:local
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /docs
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 15